### ISSUE TITLE
[BUG] Gradio script: cannot import name 'save_video_grid' from 'hyvideo.utils.file_utils'

### ISSUE THREAD

**Issue by pickettd** [gregcmartin/HunyuanVideo_MLX#11]
**System Information**
- macOS Version: 15.0
- Mac Model (M1/M2/M3): M1 Ultra
- RAM: 128gb
- MLX Version: 0.21.1
- Python Version: 3.11.11

**Describe the Bug**
After cloning the project and installing dependencies, I tried running `python gradio_server.py` and immediately got the error cannot import name 'save_video_grid' from 'hyvideo.utils.file_utils'

**To Reproduce**
`python gradio_server.py`

**Error Message/Logs**
```
gradio_server.py", line 9, in <module>
    from hyvideo.utils.file_utils import save_video_grid
ImportError: cannot import name 'save_video_grid' from 'hyvideo.utils.file_utils'
```

**Expected Behavior**
Gradio server to launch.

**Comment by gregcmartin** [comment]
Just pushed a fix for this thanks for reporting
