### ISSUE TITLE
[BUG] sample_video_mps.py: TypeError: expected np.ndarray (got list)

### ISSUE THREAD

**Issue by pickettd** [gregcmartin/HunyuanVideo_MLX#12]
**System Information**
- macOS Version: 15.0
- Mac Model (M1/M2/M3): M1 Ultra
- RAM: 128gb
- MLX Version: 0.21.1
- Python Version: 3.11.11

**Describe the Bug**
After cloning the project and installing dependencies, I tried running the example from the readme for sample_video_mps.py (limited to 20 steps). After almost an hour of GPU and memory utilization (I assume video was being generated), I got this error TypeError: expected np.ndarray (got list)

**To Reproduce**
```
python sample_video_mps.py \
    --prompt "cat riding a unicycle, realistic" \
    --video-size 544 960 \
    --video-length 13 \
    --precision fp16 \
    --vae-precision fp16 \
    --text-encoder-precision fp16 \
    --text-encoder-precision-2 fp16 --num-inference-steps 20
```

**Error Message/Logs**
```
2024-12-21 06:27:04.067 | INFO     | hyvideo.diffusion.pipelines.pipeline_hunyuan_video:__call__:733 - Target latents shape: (1, 16, 13, 68, 120)
2024-12-21 07:12:01.380 | ERROR    | hyvideo.diffusion.pipelines.pipeline_hunyuan_video:__call__:771 - Error in VAE decoding chunk 0: expected np.ndarray (got list)
Error in VAE decoding: expected np.ndarray (got list)
Error in post-processing: expected np.ndarray (got list)
Error in generation: expected np.ndarray (got list)
2024-12-21 07:12:01.427 | ERROR    | hyvideo.inference:predict:411 - Generation failed: expected np.ndarray (got list)
2024-12-21 07:12:01.427 | ERROR    | __main__:main:174 - Error occurred: expected np.ndarray (got list)
```

**Additional Context**
- Video resolution used: 544x960
- Number of frames: 13
- Prompt used: "cat riding a unicycle, realistic"
- Any environment variables set: default

**Comment by TheBrinkOfTomorrow** [comment]
I've replicated the exact same issue/bug.  [ Mac mini M4 Pro w/ 64 GB RAM ]

**Comment by gregcmartin** [comment]
just pushed and update to fix this bug, please retest and let me know

**Comment by gregcmartin** [comment]
closing as this should be resolved now

**Comment by scalar27** [comment]
This fix is not working for me.

**Comment by andi-808** [comment]
> This fix is not working for me.

The same for me.

**Comment by pickettd** [comment]
I left a comment in this issue about I branch I made that tries to fix little bugs that my machine encounters with the repo. My branch doesn't correctly generate video or images but it resolves the console errors. I just used 3.5 Sonnet to give me code to fix the errors - I don't actually know anything about MLX/torch/etc. Maybe it is a starting point for someone haha https://github.com/gregcmartin/HunyuanVideo_MLX/issues/13

**Comment by andi-808** [comment]
It also takes around an hour to fail for me, 64GB M3, as it is using around 20-30GB of swap, even using the 4bit quant prompt on the main page does not help much.

**Comment by scalar27** [comment]
While debugging, use something quicker like this:
python sample_video_mps.py \
    --prompt "a puppy frolicking in a field" \
    --video-size 384 384 \
    --video-length 1 \
    --num-inference-steps 20 \
    --enable-quantization \
    --quantization-bits 4 \
    --exclude-from-quantization vae embedders

**Comment by andi-808** [comment]
> While debugging, use something quicker like this: python sample_video_mps.py --prompt "a puppy frolicking in a field" --video-size 384 384 --video-length 1 --num-inference-steps 20 --enable-quantization --quantization-bits 4 --exclude-from-quantization vae embedders

Will try tomorrow. Cheers.

**Comment by edwios** [comment]
The fix can't be working, the type is just wrong. torch.from_numpy() expects a ndarray, not a list. I wonder how that could actually be claimed as a fix 🤔

It should be at least something like this (not saying this _is_ the solution but at least the type is correct.):
`x = torch.from_numpy(np.array(x.astype(mx.float32), np.float32))`
