### ISSUE TITLE
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements_mps.txt'

### ISSUE THREAD

**Issue by randyoo** [gregcmartin/HunyuanVideo_MLX#2]
When running the one-line setup script, I get:
```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements_mps.txt'
```

The other referenced scripts also fail to be located/executed.
It also appears to expect anaconda to already be installed.
Finally, it seems the anaconda environment needs to be activated before proceeding to download model weights.

Even after resolving these issues, I still encountered issue #1 , unfortunately.

**Comment by gregcmartin** [comment]
I fixed the script to use venv instead of conda

**Comment by MrAmedeus** [comment]
Seems to download and install all good. However i am getting this error when trying to download weights:

python3 download_weights.py
Traceback (most recent call last):
  File "/Users/xxxxx/Downloads/HunyuanVideo_MLX-main/download_weights.py", line 6, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

Im also not 100% on the .env file - Still a noob to all this
Ive created a HF access token and an .env file, but im not sure on the file name or path it should be located

**Comment by randyoo** [comment]
> Seems to download and install all good. However i am getting this error when trying to download weights:
> 
> python3 download_weights.py Traceback (most recent call last): File "/Users/xxxxx/Downloads/HunyuanVideo_MLX-main/download_weights.py", line 6, in from loguru import logger ModuleNotFoundError: No module named 'loguru'
> 
> Im also not 100% on the .env file - Still a noob to all this Ive created a HF access token and an .env file, but im not sure on the file name or path it should be located

It sounds to me like you might not be in the venv.

Closing this issue since it no longer applies to the current install instructions.
